services:
  - type: web
    name: demo-j5-asm1
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    branch: main
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
    healthCheckPath: /
    
  - type: pserv
    name: demo-j5-asm1-db
    env: docker
    image: postgres:15
    plan: free
    region: singapore
    branch: main
    envVars:
      - key: POSTGRES_DB
        value: demo_j5_asm1
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        generateValue: true
